version: '3.8'
services: 
  micro-blog-app:
    privileged: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - accendero

networks: 
  accendero:
    name: nat
